# Generated by Django 6.0.6 on 2026-06-17 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('privato', 'Privato'), ('azienda', 'Azienda')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('citta', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('ruolo', models.CharField(blank=True, max_length=50)),
                ('stipendio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('paese', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('paese', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'marche',
            },
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='azienda', serialize=False, to='gestionale.cliente')),
                ('partita_iva', models.CharField(max_length=11, unique=True)),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('settore', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Privato',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='privato', serialize=False, to='gestionale.cliente')),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_nascita', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modello', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('anno', models.PositiveIntegerField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('disponibile', 'Disponibile'), ('venduta', 'Venduta'), ('manutenzione', 'In manutenzione')], default='disponibile', max_length=20)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto', to='gestionale.fornitore')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto', to='gestionale.marca')),
            ],
            options={
                'verbose_name_plural': 'auto',
            },
        ),
        migrations.CreateModel(
            name='Manutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intervento', models.DateField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=100)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni', to='gestionale.auto')),
            ],
            options={
                'ordering': ['-data_intervento'],
            },
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vendita', models.DateField()),
                ('importo_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendite', to='gestionale.cliente')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendite', to='gestionale.dipendente')),
            ],
            options={
                'verbose_name_plural': 'vendite',
                'ordering': ['-data_vendita'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioVendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettagli_vendita', to='gestionale.auto')),
                ('vendita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='gestionale.vendita')),
            ],
            options={
                'verbose_name_plural': 'dettagli vendita',
                'constraints': [models.UniqueConstraint(fields=('vendita', 'auto'), name='unique_vendita_auto')],
            },
        ),
    ]
